# Generated by Django 5.1.3 on 2024-12-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_alter_book_options_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
