# Generated by Django 5.1.3 on 2024-12-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0006_alter_book_author_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="finished_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="is_it_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
