# Generated by Django 5.1.3 on 2024-12-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0007_book_finished_date_book_is_it_read_book_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="is_it_read",
            new_name="finished",
        ),
    ]
