# Generated by Django 5.1.3 on 2024-12-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0008_rename_is_it_read_book_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="finished_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
