# Generated by Django 5.1.3 on 2024-12-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0009_alter_book_finished_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="review",
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
